select
    act_code as act_code,
    act_entry2biz_cal_hdr as act_entry2biz_cal_hdr,
    act_entry2bug as act_entry2bug,
    act_entry2case as act_entry2case,
    act_entry2commit_log as act_entry2commit_log,
    act_entry2contact as act_entry2contact,
    act_entry2contract as act_entry2contract,
    act_entry2contr_itm as act_entry2contr_itm,
    act_entry2count_setup as act_entry2count_setup,
    act_entry2demand_dtl as act_entry2demand_dtl,
    act_entry2disptchfe as act_entry2disptchfe,
    act_entry2doc_inst as act_entry2doc_inst,
    act_entry2email_log as act_entry2email_log,
    act_entry2employee as act_entry2employee,
    act_entry2escalation as act_entry2escalation,
    act_entry2exchange as act_entry2exchange,
    act_entry2exch_log as act_entry2exch_log,
    act_entry2job as act_entry2job,
    act_entry2notes_log as act_entry2notes_log,
    act_entry2onsite_log as act_entry2onsite_log,
    act_entry2opportunity as act_entry2opportunity,
    act_entry2part_trans as act_entry2part_trans,
    act_entry2phone_log as act_entry2phone_log,
    act_entry2probdesc as act_entry2probdesc,
    act_entry2reject_msg as act_entry2reject_msg,
    act_entry2resrch_log as act_entry2resrch_log,
    act_entry2schedule as act_entry2schedule,
    act_entry2site as act_entry2site,
    act_entry2site_part as act_entry2site_part,
    act_entry2slm_log as act_entry2slm_log,
    act_entry2subcase as act_entry2subcase,
    act_entry2task as act_entry2task,
    act_entry2user as act_entry2user,
    act_entry2workaround as act_entry2workaround,
    act_entry_child2parent as act_entry_child2parent,
    addnl_info as addnl_info,
    to_char(copy_date, 'YYYY-MM-DD') as copy_date_view,
    dev as dev,
    end_date as end_date,
    entry_name2gbst_elm as entry_name2gbst_elm,
    entry_time as entry_time,
    focus_lowid as focus_lowid,
    focus_strid as focus_strid,
    focus_type as focus_type,
    objid as objid,
    proxy as proxy,
    removed as removed,
    start_date as start_date,
    copy_date as copy_date
from
    sha1_siiam.act_entry
where
    copy_date >= to_date('{{ previous_nominalDate }}', 'yyyy-mm-dd')
    and copy_date < to_date('{{ current_nominalDate }}', 'yyyy-mm-dd')